#ifndef P303ENVELOPE
#define P303ENVELOPE

enum {EA_STOP=0,EA_ATTACK,EA_SUSTAIN,EA_RELEASE,__EASTAGECOUNT};

enum {EF_STOP=0,EF_ATTACK,EF_DECAY,__EFSTAGECOUNT};


#define FILTER_REATTACKTIME 10

#define AMP_ATTACKTIME 80

#define AMP_REATTACKTIME 40

#define AMP_RELEASETIME 260
#define EXTRA_RELEASE 20


#endif
