/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : IFsh1.c
**     Project     : KL02AudioBoot
**     Processor   : MKL02Z32VFM4
**     Component   : IntFLASH
**     Version     : Component 02.409, Driver 01.02, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-09-06, 01:02, # CodeGen: 42
**     Abstract    :
**         This component "IntFLASH" implements an access to internal FLASH.
**         The component support reading/writing data into FLASH, erasing of
**         selected sector.
**         The component supports events if the write interrupt is supported.
**         The component supports following modes of write operations:
**           - Write - writing without any test.
**           - Destructive write - sector is erased if necessary.
**           - Safe write - user event is invoked to save and resore data
**                          from the current sector.
**         The component requires on-chip FLASH memory (not used/allocated by
**         other components).
**     Settings    :
**          Component name                                 : IFsh1
**          FLASH                                          : FTFA
**          FLASH_LDD                                      : FLASH_LDD
**          Write method                                   : Destructive write (with erase)
**          Interrupt service/event                        : Enabled
**            Command complete interrupt                   : 
**              Interrupt                                  : INT_FTFA
**              Interrupt priority                         : maximal priority
**          Wait in RAM                                    : yes
**          Virtual page                                   : Disabled
**          Initialization                                 : 
**            Events enabled in init.                      : yes
**            Wait enabled in init.                        : yes
**          CPU clock/speed selection                      : 
**            FLASH clock                                  : 
**            High speed mode                              : This component enabled
**            Low speed mode                               : This component disabled
**            Slow speed mode                              : This component disabled
**     Contents    :
**         DisableEvent  - byte IFsh1_DisableEvent(void);
**         EnableEvent   - byte IFsh1_EnableEvent(void);
**         EraseFlash    - byte IFsh1_EraseFlash(byte Block);
**         EraseSector   - byte IFsh1_EraseSector(IFsh1_TAddress Addr);
**         SetBlockFlash - byte IFsh1_SetBlockFlash(IFsh1_TDataAddress Source, IFsh1_TAddress Dest, word...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file IFsh1.c
** @version 01.02
** @brief
**         This component "IntFLASH" implements an access to internal FLASH.
**         The component support reading/writing data into FLASH, erasing of
**         selected sector.
**         The component supports events if the write interrupt is supported.
**         The component supports following modes of write operations:
**           - Write - writing without any test.
**           - Destructive write - sector is erased if necessary.
**           - Safe write - user event is invoked to save and resore data
**                          from the current sector.
**         The component requires on-chip FLASH memory (not used/allocated by
**         other components).
*/         
/*!
**  @addtogroup IFsh1_module IFsh1 module documentation
**  @{
*/         

/* MODULE IFsh1. */

#include "Events.h"
#include "IFsh1.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Internal method prototypes */

#define IFsh1_TOTAL_FLASH_BLOCK_COUNT  0x01U
#define IFsh1_P_FLASH_SIZE             0x8000U
#define IFsh1_P_FLASH_BLOCK_COUNT      0x01U
#define IFsh1_P_FLASH_BLOCK_SIZE       0x8000U

#define IFsh1_CMD_NONE                 0x00U
#define IFsh1_CMD_READ                 0x01U
#define IFsh1_CMD_ERASE_SECTOR         0x02U
#define IFsh1_CMD_ERASE_BLOCK          0x03U
#define IFsh1_CMD_VERIFY_ERASED_BLOCK  0x04U
#define IFsh1_CMD_WRITE                0x05U
#define IFsh1_CMD_WRITE_ERASE          0x06U

typedef struct IFsh1_TSector_Struct {
  uint32_t Data[IntFlashLdd1_ERASABLE_UNIT_SIZE/4U];
} IFsh1_TSector;

static uint32_t IFsh1_CurrentCommand;  /* Current command */
static bool IFsh1_CmdResult;           /* Last command result */
static bool IFsh1_CmdPending;          /* Current command state */
static bool IFsh1_EnEvent;             /* State of events (enabled/disabled) */

static LDD_TDeviceData* IntFlashLdd1_DevDataPtr;
static LDD_TData *IFsh1_DataAddress;
static LDD_FLASH_TAddress IFsh1_FlashAddress;
static LDD_FLASH_TDataSize IFsh1_DataSize;

byte IFsh1_SetFlash(IFsh1_TDataAddress Source, IFsh1_TAddress Dest, word Count);

/*
** ===================================================================
**     Method      :  IFsh1_SetFlash (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
byte IFsh1_SetFlash(IFsh1_TDataAddress Src, IFsh1_TAddress Dst, word Count)
{
  LDD_TError                 Result;
  uint32_t                   x;

  if (IFsh1_CmdPending) {
    return ERR_BUSY;
  }
  for (x=0U; x<Count; x++) {           /* Check if written area is erased */
    if (((uint8_t*)Dst)[x] != 0xFFU) { /* Byte erased? */
      IFsh1_CurrentCommand = IFsh1_CMD_WRITE_ERASE;
      IFsh1_CmdPending = TRUE;
      IFsh1_DataAddress = (LDD_TData *)Src;
      IFsh1_FlashAddress = Dst;
      IFsh1_DataSize = Count;
      Result = IntFlashLdd1_Erase(IntFlashLdd1_DevDataPtr, (LDD_FLASH_TAddress)(Dst & ~(LDD_FLASH_TAddress)IntFlashLdd1_ERASABLE_UNIT_MASK), IntFlashLdd1_ERASABLE_UNIT_SIZE);
      if (Result == ERR_OK) {
        do {
        } while (IFsh1_CmdPending);
        Result = IFsh1_CmdResult;
      } else {
        IFsh1_CmdPending = FALSE;      /* Command parameter error */
        if (Result == ERR_PARAM_ADDRESS) {
          Result = ERR_RANGE;
        }
      }
      return (byte)Result;
    }
  }
  IFsh1_CurrentCommand = IFsh1_CMD_WRITE;
  IFsh1_CmdPending = TRUE;
  Result = IntFlashLdd1_Write(IntFlashLdd1_DevDataPtr, (LDD_TData *)Src, Dst, (LDD_FLASH_TDataSize)Count); /* Start reading from the flash memory */
  if (Result == ERR_OK) {
    do {
    } while (IFsh1_CmdPending);
    Result = IFsh1_CmdResult;
  } else {
    IFsh1_CmdPending = FALSE;          /* Command parameter error */
    if (Result == ERR_PARAM_ADDRESS) {
      Result = ERR_RANGE;
    }
  }
  return (byte)Result;
}

/*
** ===================================================================
**     Method      :  IFsh1_Init (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IFsh1_Init(void)
{
  IntFlashLdd1_DevDataPtr = IntFlashLdd1_Init(NULL);
  IFsh1_CmdPending = FALSE;
  IFsh1_EnEvent = TRUE;                /* Remember events state */
}

/*
** ===================================================================
**     Method      :  IFsh1_DisableEvent (component IntFLASH)
*/
/*!
**     @brief
**         This method disables all the events except [OnSaveBuffer],
**         [OnRestoreBuffer] and [OnEraseError]. The method is
**         available only if any event is enabled.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte IFsh1_DisableEvent(void)
{
  IFsh1_EnEvent = FALSE;
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  IFsh1_EnableEvent (component IntFLASH)
*/
/*!
**     @brief
**         This method enables all the events except [OnSaveBuffer],
**         [OnRestoreBuffer] and [OnEraseError]. The method is
**         available only if any event is enabled.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte IFsh1_EnableEvent(void)
{
  IFsh1_EnEvent = TRUE;
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  IFsh1_EraseFlash (component IntFLASH)
*/
/*!
**     @brief
**         Erases entire memory array of the selected Flash block.
**     @param
**         Block           - Block number of the Flash memory block
**                           that will be erased. Number is in range
**                           zero to maximum available block number. Not
**                           used for Freescale 56800 derivates except
**                           for the Program_Boot_Flash on 56F83xx and
**                           56F81xx derivatives. If the flash memory
**                           contais only one block, this parameter is
**                           ignored.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - Block number is out of range 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode 
**                           - ERR_BUSY - Device is busy 
**                           - ERR_VALUE - Flash erase was not successful
*/
/* ===================================================================*/
byte IFsh1_EraseFlash(byte Block)
{
  LDD_TError                 Result;

  if (IFsh1_CmdPending) {
    return ERR_BUSY;
  }
  IFsh1_CurrentCommand = IFsh1_CMD_ERASE_BLOCK;
  IFsh1_CmdPending = TRUE;
  Result = IntFlashLdd1_EraseBlock(IntFlashLdd1_DevDataPtr, ((LDD_FLASH_TAddress)Block * IFsh1_P_FLASH_BLOCK_SIZE));
  if (Result == ERR_OK) {
    do {
    } while (IFsh1_CmdPending);
    Result = IFsh1_CmdResult;
  } else {
    IFsh1_CmdPending = FALSE;          /* Command parameter error */
    if (Result == ERR_PARAM_ADDRESS) {
      Result = ERR_RANGE;
    }
  }
  return (byte)Result;
}

/*
** ===================================================================
**     Method      :  IFsh1_EraseSector (component IntFLASH)
*/
/*!
**     @brief
**         Erases the sector to which address Addr belongs.
**     @param
**         Addr            - Address in FLASH.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - Address is out of range 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode 
**                           - ERR_BUSY - Device is busy 
**                           - ERR_PROTECT - Flash is write protect 
**                           - ERR_VALUE - Flash sector erase was not
**                           successful
*/
/* ===================================================================*/
byte IFsh1_EraseSector(IFsh1_TAddress Addr)
{
  LDD_TError                 Result;

  if (IFsh1_CmdPending) {
    return ERR_BUSY;
  }
  IFsh1_CurrentCommand = IFsh1_CMD_ERASE_SECTOR;
  IFsh1_CmdPending = TRUE;
  Result = IntFlashLdd1_Erase(IntFlashLdd1_DevDataPtr, (LDD_FLASH_TAddress)(Addr & ~(LDD_FLASH_TAddress)IntFlashLdd1_ERASABLE_UNIT_MASK), IntFlashLdd1_ERASABLE_UNIT_SIZE);
  if (Result == ERR_OK) {
    do {
    } while (IFsh1_CmdPending);
    Result = IFsh1_CmdResult;
  } else {
    IFsh1_CmdPending = FALSE;          /* Command parameter error */
    if (Result == ERR_PARAM_ADDRESS) {
      Result = ERR_RANGE;
    }
  }
  return (byte)Result;
}

/*
** ===================================================================
**     Method      :  IFsh1_SetBlockFlash (component IntFLASH)
*/
/*!
**     @brief
**         Writes data to FLASH. The operation of this method depends
**         on the "Write method" property and state of the flash.
**         Please see more details on general info page of the help.
**     @param
**         Source          - Source address of the data.
**     @param
**         Dest            - Destination address in FLASH.
**     @param
**         Count           - Count of the data fields (in the
**                           smallest addressable units).
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - The address is out of range 
**                           - ERR_BUSY - Device is busy 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode 
**                           - ERR_PROTECT - Flash is write protect 
**                           - ERR_VALUE - Read value is not equal to
**                           written value
*/
/* ===================================================================*/
byte IFsh1_SetBlockFlash(IFsh1_TDataAddress Source, IFsh1_TAddress Dest, word Count)
{
  return IFsh1_SetFlash(Source, Dest, Count);
}

/*
** ===================================================================
**     Method      :  IFsh1_OnOperationComplete (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IntFlashLdd1_OnOperationComplete(LDD_TUserData *UserDataPtr)
{
  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  IFsh1_CmdResult = ERR_OK;            /* No error appears */
  switch (IFsh1_CurrentCommand) {
    case IFsh1_CMD_WRITE_ERASE:
      IFsh1_CurrentCommand = IFsh1_CMD_WRITE;
      IFsh1_CmdResult = (byte)IntFlashLdd1_Write(IntFlashLdd1_DevDataPtr, IFsh1_DataAddress, IFsh1_FlashAddress, IFsh1_DataSize); /* Start reading from the flash memory */
      if (IFsh1_CmdResult != ERR_OK) { /* Write command error? */
        IFsh1_CmdPending = FALSE;      /* Command is finished */
      }
      return;
    case IFsh1_CMD_WRITE:
      IFsh1_CmdPending = FALSE;        /* Command is finished */
      break;
    default:
      IFsh1_CmdPending = FALSE;        /* Command is finished */
      return;
  }
  if (IFsh1_EnEvent == TRUE) {
    IFsh1_OnWriteEnd();
  }
}

/*
** ===================================================================
**     Method      :  IFsh1_OnError (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IntFlashLdd1_OnError(LDD_TUserData *UserDataPtr)
{
  LDD_FLASH_TErrorStatus FLASH_LDD_ErrorStatus;

  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  IFsh1_CmdPending = FALSE;
  IFsh1_CurrentCommand = IFsh1_CMD_NONE;
  IntFlashLdd1_GetError(IntFlashLdd1_DevDataPtr, &FLASH_LDD_ErrorStatus);
  if (FLASH_LDD_ErrorStatus.CurrentErrorFlags & LDD_FLASH_PROTECTION_VIOLATION) {
    IFsh1_CmdResult = ERR_PROTECT;     /* Protection violation */
  } else {
    IFsh1_CmdResult = ERR_VALUE;       /* Access error or Read collision error */
  }
}

/* END IFsh1. */

#ifdef __cplusplus
}  /* extern "C" */
#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
